# Generated by Django 6.1.2 on 2026-10-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.PositiveIntegerField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='telemetry.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('recv_ts_utc', models.DateTimeField()),
                ('host_time', models.BigIntegerField(blank=True, null=True)),
                ('hdc_temp_x10', models.IntegerField(blank=True, null=True)),
                ('hdc_hum_x10', models.IntegerField(blank=True, null=True)),
                ('light_raw', models.IntegerField(blank=True, null=True)),
                ('bmp_temp_x10', models.IntegerField(blank=True, null=True)),
                ('pressure_pa', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.gateway')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.node')),
            ],
            options={
                'ordering': ['-recv_ts_utc'],
            },
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('gateway', 'node_id'), name='uniq_gateway_node'),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='uniq_gateway_event'),
        ),
    ]
